// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FofaStat(arg1:string):Promise<main.Result>;

export function StartTask(arg1:string,arg2:string):Promise<main.Result>;

export function UpdateConfig(arg1:string,arg2:number):Promise<main.Result>;

export function UpdateScore(arg1:string,arg2:Array<string>,arg3:number):Promise<main.Result>;
