// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartTask(arg1, arg2) {
  return window['go']['main']['App']['StartTask'](arg1, arg2);
}

export function UpdateScore(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateScore'](arg1, arg2, arg3);
}
